# Generated by Django 5.0.6 on 2024-06-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetoken',
            name='solana_token_address',
        ),
    ]
